### ISSUE TITLE
Allow various aspects of the extension to be configurable

### ISSUE THREAD

**Issue by markcarver** [rezozero/commonmark-ext-footnotes#7]
Many of the CommonMark extensions have the ability to customize certain aspects of their extension, namely around classes and the like:

https://github.com/thephpleague/commonmark/blob/1.4/src/Extension/HeadingPermalink/HeadingPermalinkRenderer.php#L44

It would be nice if this could do the same.

**Comment by fenetikm** [comment]
As a starting point, what would be great is the ability to specify the prefix for the anchors i.e. `fnref:` and `fn:`. Ideally this could be left blank / empty.

**Comment by markcarver** [comment]
Closing this in favor of https://github.com/thephpleague/commonmark/pull/484
