### ISSUE TITLE
Archive project

### ISSUE THREAD

**Issue by markcarver** [rezozero/commonmark-ext-footnotes#8]
https://github.com/thephpleague/commonmark/releases/tag/1.5.0

This release includes this project. This project can now be archived.

Thank you again!

**Comment by nonoesp** [comment]
Awesome to see this work integrated on the CommonMark project! 🥳

**Comment by markhalliwell** [comment]
@ambroisemaupate this entire project can now be archived on GH too (https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories)
